# Generated by Django 3.0.2 on 2020-03-31 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('l_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=100)),
                ('x_cord', models.FloatField()),
                ('y_cord', models.FloatField()),
                ('times_cleaned', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cleaned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cleaned', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('l_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Location')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
