# Generated by Django 3.0.2 on 2020-04-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
